# @package _global_
job_name: pluto_boston
py_func: train
objective_aggregate_mode: mean

defaults:
  - override /data_augmentation: contrastive_scenario_generator
  - override /splitter: ratio_splitter
  - override /model: pluto_model
  - override /scenario_builder: nuplan_boston
  - override /scenario_filter: training_scenarios_boston
  - override /custom_trainer: pluto_trainer
  - override /lightning: custom_lightning
